name: Automação Selenium Java

on:
  push:
    paths:
      - 'selenium-java/**'
      - '.github/workflows/selenium.yml'

  pull_request:
    paths:
      - 'selenium-java/**'
      - '.github/workflows/selenium.yml'

  workflow_dispatch:

jobs:
  selenium:
    name: Testes Selenium Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v7

      - name: Configurar Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Executar testes Selenium
        working-directory: selenium-java
        run: mvn test